source 'https://rubygems.org' # rubocop:disable Style/FileName

ruby '2.4.1'

gem 'bigdecimal'
gem 'json'
gem 'puma'
gem 'rails', '~> 5.0'

platforms :ruby do
  gem 'pg'
  gem 'pry-byebug'
  gem 'ruby-prof'
end

platforms :jruby do
  gem 'activerecord-jdbc-adapter'
  gem 'jdbc-pg'
  gem 'jruby-openssl'
end

# gem 'sidekiq-unique-jobs'
gem 'rack-protection' # , github: 'sinatra/rack-protection'
gem 'sidekiq-unique-jobs', path: '../'
gem 'sinatra', github: 'sinatra/sinatra'

group :development do
  gem 'web-console'
end

group :development, :test do
  gem 'dockerspec'
  gem 'factory_girl_rails'
  gem 'fuubar'
  gem 'mock_redis'
  gem 'rspec-rails'
end
