# frozen_string_literal: true

source "https://rubygems.org"

ruby "2.5.5"

gem "bigdecimal"
gem "json"
gem "pg"
gem "puma"
gem "rack-protection"
gem "rails", "~> 5.2"
gem "sidekiq"
gem "sidekiq-unique-jobs", path: ".."
gem "sinatra"
gem "slim-rails"

group :development, :test do
  gem "capybara"
  gem "dotenv-rails"
  gem "factory_bot_rails"
  gem "fuubar"
  gem "pry-byebug"
  gem "pry-rails"
  gem "rspec-eventually"
  gem "rspec-rails"
  gem "rubocop"
  gem "rubocop-performance"
  gem "rubocop-rspec"
end
