---
version: '2'
plugins:
  duplication:
    enabled: true
    config:
      languages:
        - ruby
  fixme:
    enabled: true
  flog:
    enabled: true
  markdownlint:
    enabled: true
  reek:
    enabled: true
    config:
      file: .reek.yml
  rubocop:
    enabled: true
    channel: rubocop-0-67
    config:
      file: .rubocop.yml

exclude_patterns:
  - "Gemfile"
  - "*.gemspec"
  - "Appraisals"
  - "gemfiles/"
  - "rails_example/"
  - "redis/"
  - "tmp/"
