---
exclude_paths:
  - my_app
  - redis
  - spec
  - tmp
  - gemfiles
  - examples
  - vendor/bundle
detectors:
  DuplicateMethodCall:
    exclude:
    - Sidekiq#self.use_options
    - SidekiqUniqueJobs::Lock::WhileExecuting#execute
    - SidekiqUniqueJobs::Profiler#self.stop
    - SidekiqUniqueJobs::Timing#timed
    - SidekiqUniqueJobs::Web#self.registered
  IrresponsibleModule:
    enabled: false
  LongParameterList:
    enabled: true
    exclude:
    - initialize
    - Hash#slice
    - SidekiqUniqueJobs::ClientMiddleware#call
  TooManyStatements:
    exclude:
    - initialize
    - Hash#slice
    - SidekiqUniqueJobs::ClientMiddleware#call
    - SidekiqUniqueJobs::Digests#batch_delete
    - SidekiqUniqueJobs::Digests#delete_by_pattern
    - SidekiqUniqueJobs::Lock::WhileExecuting#execute
    - SidekiqUniqueJobs::Locksmith#try_lock
    - SidekiqUniqueJobs::Profiler#self.stop
    - SidekiqUniqueJobs::Middleware#self.configure_server
    - SidekiqUniqueJobs::Middleware#with_logging_context
    - SidekiqUniqueJobs::Scripts#call
    - SidekiqUniqueJobs::ServerMiddleware#call
    - SidekiqUniqueJobs::UniqueArgs#filtered_args
    - SidekiqUniqueJobs::Util#del
    - SidekiqUniqueJobs::Web#self.registered
  UncommunicativeVariableName:
    exclude:
    - Hash#slice
  BooleanParameter:
    exclude:
    - SidekiqUniqueJobs::Cli#self.banner
  UtilityFunction:
    enabled: false
  TooManyConstants:
    exclude:
    - SidekiqUniqueJobs
  ManualDispatch:
    enabled: true
    exclude:
    - Hash#slice
    - Hash#slice!
    - SidekiqUniqueJobs::Middleware#with_configured_loggers_context
    - SidekiqUniqueJobs::OnConflict::Reject#deadset_kill?
    - SidekiqUniqueJobs::SidekiqWorkerMethods#worker_method_defined?
    - SidekiqUniqueJobs::Web::Helpers#redirect_to
  MissingSafeMethod:
    exclude:
    - Array
  NilCheck:
    enabled: false
  DataClump:
    enabled: true
    exclude:
      - SidekiqUniqueJobs::Util
  FeatureEnvy:
    exclude:
    - SidekiqUniqueJobs::Digests#batch_delete
    - SidekiqUniqueJobs::Digests#page
    - SidekiqUniqueJobs::Logging#debug_item
    - SidekiqUniqueJobs::OnConflict::Reject#push_to_deadset
    - SidekiqUniqueJobs::Util#batch_delete
    - SidekiqUniqueJobs::Web::Helpers#cparams
  NestedIterators:
    exclude:
    - SidekiqUniqueJobs::Digests#batch_delete
    - SidekiqUniqueJobs::Locksmith#create_lock
    - SidekiqUniqueJobs::Middleware#self.configure_client
    - SidekiqUniqueJobs::Middleware#self.configure_server
    - SidekiqUniqueJobs::Util#batch_delete
    - SidekiqUniqueJobs::Util#keys_with_ttl
  TooManyInstanceVariables:
    exclude:
    - SidekiqUniqueJobs::Locksmith
    - SidekiqUniqueJobs::Key
  TooManyMethods:
    exclude:
    - SidekiqUniqueJobs::Locksmith
    - SidekiqUniqueJobs::Lock::BaseLock
