---
exclude_paths:
  - rails_example
  - redis
  - spec
  - tmp
  - gemfiles
  - examples
  - vendor/bundle
detectors:
  DuplicateMethodCall:
    exclude:
    - Sidekiq#self.use_options
    - SidekiqUniqueJobs::Web#self.registered
  IrresponsibleModule:
    enabled: false
  LongParameterList:
    enabled: true
    exclude:
    - initialize
    - Hash#slice
    - SidekiqUniqueJobs::Locksmith#create_lock
    - SidekiqUniqueJobs::Locksmith#expire_when_necessary
    - SidekiqUniqueJobs::Client::Middleware#call
  TooManyStatements:
    exclude:
    - initialize
    - Hash#slice
    - SidekiqUniqueJobs::Locksmith#create_lock
    - SidekiqUniqueJobs::Locksmith#expire_when_necessary
    - SidekiqUniqueJobs::Middleware#configure_server_middleware
    - SidekiqUniqueJobs::Server::Middleware#call
    - SidekiqUniqueJobs::UniqueArgs#filtered_args
    - SidekiqUniqueJobs::Util#del
    - SidekiqUniqueJobs::Digests#batch_delete
    - SidekiqUniqueJobs::Digests#delete_by_pattern
    - SidekiqUniqueJobs::Web#self.registered
  UncommunicativeVariableName:
    exclude:
    - Hash#slice
  BooleanParameter:
    exclude:
    - SidekiqUniqueJobs::Cli#self.banner
  UtilityFunction:
    enabled: false
  TooManyConstants:
    exclude:
    - SidekiqUniqueJobs
  ManualDispatch:
    enabled: true
    exclude:
    - Hash#slice
    - Hash#slice!
    - SidekiqUniqueJobs::OnConflict::Reject#deadset_kill?
    - SidekiqUniqueJobs::SidekiqWorkerMethods#worker_method_defined?
    - SidekiqUniqueJobs::Web::Helpers#redirect_to
  MissingSafeMethod:
    exclude:
    - Array
  NilCheck:
    enabled: false
  DataClump:
    enabled: true
    exclude:
      - SidekiqUniqueJobs::Util
  FeatureEnvy:
    exclude:
    - SidekiqUniqueJobs::Digests#batch_delete
    - SidekiqUniqueJobs::Digests#page
    - SidekiqUniqueJobs::Logging#debug_item
    - SidekiqUniqueJobs::OnConflict::Reject#push_to_deadset
    - SidekiqUniqueJobs::Util#batch_delete
    - SidekiqUniqueJobs::Web::Helpers#cparams
  NestedIterators:
    exclude:
    - SidekiqUniqueJobs::Digests#batch_delete
    - SidekiqUniqueJobs::Locksmith#create_lock
    - SidekiqUniqueJobs::Middleware#configure_client_middleware
    - SidekiqUniqueJobs::Middleware#configure_server_middleware
    - SidekiqUniqueJobs::Util#batch_delete
    - SidekiqUniqueJobs::Util#keys_with_ttl
  TooManyInstanceVariables:
    exclude:
    - SidekiqUniqueJobs::Locksmith
  TooManyMethods:
    exclude:
    - SidekiqUniqueJobs::Locksmith
    - SidekiqUniqueJobs::Lock::BaseLock
