inherit_gem:
  rubocop-mhenrixon:
    - config/default.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Include:
    - "examples/**/*.rb"
  Exclude:
    - "**/*.erb"
    - "**/*.lua"
    - '**/vendor/**/*'
    - "bin/bench"

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/LineLength:
  Exclude:
    - myapp/db/**/*.rb
    - myapp/config/initializers/devise.rb

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Lint/EmptyBlock:
  Exclude:
    - spec/**/*

Lint/SuppressedException:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Metrics/AbcSize:
  Max: 38

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/MethodLength:
  Max: 13
  Exclude:
    - myapp/db/**/*.rb
    - myapp/config/initializers/devise.rb

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - "myapp/db/**/*.rb"
    - "**/spec/**/*.rb"
    - "**/*.rake"
    - "Rakefile"
    - "*.gemspec"

Metrics/PerceivedComplexity:
  Max: 8

Naming/AccessorMethodName:
  Enabled: true

Naming/ConstantName:
  Enabled: true

Naming/FileName:
  Enabled: true
  Exclude:
    - lib/sidekiq-unique-jobs.rb
    - Gemfile
    - Rakefile
    - myapp/Gemfile
    - myapp/Rakefile

Naming/RescuedExceptionsVariableName:
  PreferredName: ex

Naming/MethodParameterName:
  AllowedNames:
    - ex

RSpec/ContextWording:
  Enabled: true
  Prefixes:
    - when
    - with
    - without
    - if
    - unless
    - for
    - that
    - and

RSpec/DescribeClass:
  Exclude:
    - spec/sidekiq/api_spec.rb
    - spec/sidekiq_unique_jobs/core_ext_spec.rb
    - spec/sidekiq_unique_jobs/lua/**/*_spec.rb

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectActual:
  Enabled: false

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/FilePath:
  Enabled: true
  Exclude:
    - spec/performance/locksmith_spec.rb
    - spec/performance/lock_digest_spec.rb

RSpec/InstanceVariable:
  Exclude:
    - spec/sidekiq_unique_jobs/middleware/client/call_spec.rb
    - spec/sidekiq_unique_jobs/middleware/server/call_spec.rb

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/RepeatedExample:
  Exclude:
    - spec/sidekiq_unique_jobs/unique_args_spec.rb

Style/Documentation:
  Enabled: true
  Exclude:
    - "examples/**/*.rb"
    - "myapp/**/*.rb"
    - "bin/**/*.rb"
    - "lib/sidekiq_unique_jobs/testing.rb"
    - "lib/sidekiq_unique_jobs/core_ext.rb"
    - "lib/sidekiq_unique_jobs/sidekiq_unique_ext.rb"
    - "lib/sidekiq_unique_jobs/web/**/*"

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/StringLiteralsInInterpolation:
  Enabled: true

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Style/TernaryParentheses:
  Enabled: true
  EnforcedStyle: require_parentheses_when_complex
  AllowSafeAssignment: true

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/GlobalVars:
  Enabled: true

Style/ModuleFunction:
  Enabled: false

ThreadSafety/InstanceVariableInClassMethod:
  Exclude:
    - lib/sidekiq_unique_jobs/web.rb

