require:
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.3
  Include:
    - "**/Rakefile"
    - "**/Gemfile"
    - "*.gemspec"
    - "lib/**/*.rb"
    - "bin/**/*.rb"
    - "spec/**/*.rb"
    - "examples/**/*.rb"
  Exclude:
    - "Gemfile.lock"
    - "**/*.erb"

Lint/HandleExceptions:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Metrics/AbcSize:
  Max: 38

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 13

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - "**/spec/**/*.rb"
    - "**/*.rake"
    - "Rakefile"

Metrics/PerceivedComplexity:
  Max: 8

Naming/AccessorMethodName:
  Enabled: true

Naming/ConstantName:
  Enabled: true

Naming/FileName:
  Enabled: true

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - ex

RSpec/AlignLeftLetBrace:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectActual:
  Enabled: false

RSpec/FilePath:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 4
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/Documentation:
  Enabled: true
  Exclude:
    - "examples/**/*.rb"
    - "rails_example/**/*.rb"
    - "bin/**/*.rb"
    - "lib/sidekiq_unique_jobs/testing.rb"
    - "lib/sidekiq_unique_jobs/core_ext.rb"
    - "lib/sidekiq_unique_jobs/sidekiq_unique_ext.rb"
    - "lib/sidekiq_unique_jobs/web/**/*"
    - "lib/sidekiq_unique_jobs/on_conflict.rb"
    - "lib/sidekiq_unique_jobs/timeout.rb"

Style/GlobalVars:
  Enabled: true

Style/ModuleFunction:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/StringLiteralsInInterpolation:
  Enabled: true

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Style/TernaryParentheses:
  Enabled: true
  EnforcedStyle: require_parentheses_when_complex
  AllowSafeAssignment: true

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma
