# Stop rubocop from inheriting the parent gem's config
inherit_from: []

plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - bin/**/*
    - db/schema.rb
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*

Layout/LineLength:
  Max: 120
  Exclude:
    - db/**/*.rb

Metrics/MethodLength:
  Max: 20
  Exclude:
    - db/**/*.rb

Metrics/BlockLength:
  Exclude:
    - db/**/*.rb
    - spec/**/*.rb
    - config/**/*.rb

Metrics/AbcSize:
  Max: 30
  Exclude:
    - db/**/*.rb

Naming/MethodParameterName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
