# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "~> 3.2"

gem "rails"

gem "pg"
gem "puma"

gem "bootsnap"
gem "devise"
gem "json"
gem "rack-protection"
gem "redis"
gem "sidekiq"
gem "sidekiq-unique-jobs", path: ".."
gem "sinatra"
gem "slim-rails"

gem "cssbundling-rails"
gem "importmap-rails"
gem "sprockets-rails"
gem "stimulus-rails"
gem "turbo-rails"

group :development, :test do
  gem "dotenv-rails"
  gem "factory_bot_rails"
  gem "fuubar"
  gem "listen"
  gem "pry-rails"
  gem "rspec-rails"
end

group :development do
  gem "erb_lint", require: false
  gem "rubocop"
  gem "rubocop-mhenrixon"
  gem "rubocop-performance"
  gem "rubocop-rails"
  gem "rubocop-rake"
  gem "rubocop-rspec"
end

group :test do
  gem "capybara", require: false
  gem "capybara-playwright-driver"
end

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
