# frozen_string_literal: true

source "https://rubygems.org"

ruby ">= 3.3"

gem "rails", ">= 8.1.0"

gem "pg"
gem "propshaft"
gem "puma"

gem "bootsnap", require: false
gem "json"
gem "redis"
gem "sidekiq"
gem "sidekiq-unique-jobs", path: ".."

# Frontend
gem "importmap-rails"
gem "stimulus-rails"
gem "turbo-rails"

# Views
gem "daisyui", github: "mhenrixon/daisyui", require: "daisy_ui"
gem "phlex-rails"
gem "rails_icons", "~> 1.1"

group :development, :test do
  gem "dotenv-rails"
  gem "factory_bot_rails"
  gem "fuubar"
  gem "pry-rails"
  gem "rspec-rails"
end

group :development do
  gem "rubocop", require: false
  gem "rubocop-performance", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rake", require: false
  gem "rubocop-rspec", require: false
  gem "web-console"
end

group :test do
  gem "capybara", require: false
  gem "capybara-playwright-driver"
end

gem "tzinfo-data", platforms: [:windows, :jruby]
