# frozen_string_literal: true

source "https://rubygems.org"

ruby "2.6.5"

gem "bigdecimal"
gem "coverband"
gem "hiredis"
gem "json"
gem "pg"
gem "puma"
gem "rack-protection"
gem "rails", ">= 6.0"
gem "redis"
gem "sidekiq", "~> 6.0.0"
gem "sidekiq-cron"
gem "sidekiq-global_id"
gem "sidekiq-status"
gem "sidekiq-unique-jobs", path: ".."
gem "sinatra"
gem "slim-rails"

group :development, :test do
  gem "capybara"
  gem "dotenv-rails"
  gem "factory_bot_rails"
  gem "fuubar"
  gem "listen"
  gem "pry-byebug"
  gem "pry-rails"
  gem "rspec-rails"
  gem "rubocop"
  gem "rubocop-performance"
  gem "rubocop-rails"
  gem "rubocop-rspec"
end
