name: ci
on:
  pull_request:
  push:
    branches: [ main, v9 ]
jobs:
  coverage:
    services:
      toxiproxy:
        image: ghcr.io/shopify/toxiproxy
        ports:
          - 8474:8474
          - 21212:21212
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

  rspec:
    services:
      toxiproxy:
        image: ghcr.io/shopify/toxiproxy
        ports:
          - 8474:8474
          - 21212:21212
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        ruby: ["3.2", "3.3", "3.4", "4.0"]
        gemfile:
          - sidekiq_8.0
          - sidekiq_8.1

    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: >-
          REDIS_HOST=localhost
          TOXI_REDIS_URL=toxiproxy:21212
          TOXI_PROXY_HOST=http://toxiproxy:8474
          bin/rspec --require spec_helper --tag ~perf
